---
title: "05_analysis_2.qmd"
author: "group_12"
format:
  html:
    embed-resources: true
editor: visual
---

## Loading Libraries

```{r}
#| echo = TRUE
library(tidyverse)
library(ggplot2)
library(dplyr)
```

## Disease-outbreaks, reproducing fig4b with top 20 diseases

```{r}

#keeping the 20 most frequent diseases
#the fct_infreq orders the Disease in levels according to frequency
#the str_wraps wraps text that is over 30 characters

Fig4b_reproduced <- final_outbreaks |> 
  count(Disease) |> 
  arrange(desc(n)) |> 
  slice_head(n = 20) |>  
  inner_join(final_outbreaks, by = "Disease")  |> 
  mutate(Disease = fct_infreq(Disease))  |>  
  ggplot(mapping = aes(x = Disease)) +
  geom_bar()+
  labs(y = "Total frequency of outbreaks \n (1996 - 2021)", 
       x = "Disease") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 30)) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

Fig4b_reproduced

ggsave(Fig4b_reproduced, filename = "Results/Fig4b_reproduced.png", dpi = 300)
```

## Creating a new Figure 4b, with incorporated information on country income status

```{r}

Fig4b_income <- final_outbreaks |> 
  count(Disease) |> 
  arrange(desc(n)) |> 
  slice_head(n = 20) |> 
  inner_join(final_outbreaks, by = "Disease")  |> 
  mutate(Disease = fct_infreq(Disease)) |>
  ggplot(mapping = aes(x = Disease, fill = Income.Group)) +
  geom_bar()+
  scale_fill_brewer(palette = "Spectral") +
  labs(y = "Total frequency of outbreaks \n (1996 - 2021)", 
       x = "Disease") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 30)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 8), 
        legend.title = element_blank())

Fig4b_income

ggsave(Fig4b_income, filename = "Results/Fig4b_income.png", dpi = 300)

```

## Disease type distribution over the years 1996-2022

```{r}
Disease_distribution <- final_outbreaks |>
  drop_na() |> 
  ggplot(mapping =
           aes(x = Year,
               fill = Disease_class, 
               group = Disease_class)) +
  geom_bar(stat = "count") +
  scale_x_continuous(breaks = seq(min(final_outbreaks$Year), 
                                  max(final_outbreaks$Year), 
                                  by = 1)) +
  scale_y_continuous(breaks = seq(min(0), 
                                  max(300), 
                                  by = 20)) +  
  theme_classic() +
  scale_fill_viridis_d(alpha = 0.8) +
  theme(plot.title = element_text(size = 12,
                                  vjust = -2,
                                  hjust = 0.5),
        axis.title.x = element_text(size = 7),
        axis.title.y = element_text(size = 8),
        axis.text.x = element_text(size = 6,
                                   angle = 45),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6)) +
  labs(x = "Year",
       y = "Count of disease",
       title = "Disease type distribution over time",
       fill = "Disease classification")

ggsave(Disease_distribution, filename = "Results/Disease_distribution.png", dpi = 300)

```
